- Fixed hook call with the (alert) command tag.
**customCommands.js:**
- Cast the message as a string, also use the JavaScript `replace` method
and not Java's `replaceFirst` one.

Before:
```
lb
[12-31-2017 @ 02:12:47.334 AST] [ERROR] TypeError: Cannot find function replaceFirst in object (alert
 banana.gif,6) Dancetime!!.
```

After:
```
lb
[12-31-2017 @ 02:12:47.334 AST] [CHAT]  Dancetime!!
```